language: java
notifications:
  hipchat:
    rooms:
      secure: WQ1CmieWZokVQCAOh6D3me1//eU2bRpVQwaiu52kWWKxMyCdHUQG/87Yx5JDxCCTu9mPhZJ3Fry/ImvDLUWJUrr6nPm5ljSrks0QHJqtVoVTX/RYsCeJP3XPDc9AE4aLuUbK8OELItTZL31mVGTei0cYLNlssAr72kkeyMqSeS0zkn+GtWd79gxB3BzXiYJWJ6XIqUikZAG/fqtqFlRK1VjvfQpZ1MMEjfembipDyZeUY4fwMCpaB/8f0cHVbYEh8Ju15V+LOk5WcWUg3fYvmUR7QJB5mV/zNmbOuBSirBDZX3JZctuN/Ino7d03hV/1CPxQRMo+Za5oM6mQ9JuNHxLOqnIZMRIgweK5wuJGmPo6scX9jvnu1EbHaQL35vEi9xde4aozoZsXo8v7us8/0krPTEYYmS70Iql6LdaT9T66td//oU7GxJ/MPJU+ClmIKZn/KyeoZjS3+xLKjxxKDP0BkljEkr9gfT+DkvnnqyIZfFEq+gsV1no3NO8dDaMfD+rSvL02zibJiOlpe4VaAGn9mJ0yDEeDdCQT5Hc1PoJu2ElhBiv8YlX+y8jLJfKiVsMThJ2M66PsZIzgxDJdZ3DrQSxmSqGREZ5iYNAI9BloIqjoJtpGQx2bCQ1/MxcHENswsTJZI5mZZbRCKiqkQzyhtVt8ylAsT1Zy4N3bi50=
deploy:
  provider: releases
  api_key:
    secure: by7GjfP11OIdIPr8RBODdWZHuEjYrbs3ImpKVJ2cPkb7E5r/xGXBEKEBFBo8uRimNj09EWM5Rp29tdBXhVSvqIztp4W6jT80TLXksdbEB1eVIG1t/iKHDOS99PNj9YhU1BW/1JUm6MnZZxMvtNkbZvCevgLWdA/4n+jJZk6hLZ3gz89o48ghGod0GOYL0gBbCQzxCaJU1hQ0t8Wz653A5hDvGTHIbqnNo9BDxCDQ/5xMNezZcUq02WrlOQsjOHW3eo2cN8+f7WxQTbDbPG1YFWv17XFSjQf0QNxJFK5Sw9WjFG4jBdcq8vWdgUxNxfqEilfbVuEAHCgi7QswTwBslrYXgcQJodC3Z4AMHsQ3iK2BMOkZdiFA6ZDpItqEEovu7EOer3MSqKpimXNOpKjSMDSKylGv+HxgC2Gv1Xv66zmljL/YfaS9R8yresDyi6rAb+6KvFnHPdf1BAdpk8MJygNiDCDOlVdCIluCVnPY7RY8YRdG9NvxRslpUSlGgCzADzWb14DbLQM4eknMRT1fwQE+S+3XxvRIVRsxtfqiNuEZUN02Q6y0w6xQNZ0EukMU3IdRIAVrkFif1WgLQkoqGNj3AqMfVeWzTpbhqYMfzHdwTqX7YTrGDxqvTM1EIeRpr3l5y72Np3IFI4Xge2xABdUhFAGqLuzejQmKWbB6cmU=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-rancher-plugin

