language: java
notifications:
  hipchat:
    rooms:
      secure: WQ1CmieWZokVQCAOh6D3me1//eU2bRpVQwaiu52kWWKxMyCdHUQG/87Yx5JDxCCTu9mPhZJ3Fry/ImvDLUWJUrr6nPm5ljSrks0QHJqtVoVTX/RYsCeJP3XPDc9AE4aLuUbK8OELItTZL31mVGTei0cYLNlssAr72kkeyMqSeS0zkn+GtWd79gxB3BzXiYJWJ6XIqUikZAG/fqtqFlRK1VjvfQpZ1MMEjfembipDyZeUY4fwMCpaB/8f0cHVbYEh8Ju15V+LOk5WcWUg3fYvmUR7QJB5mV/zNmbOuBSirBDZX3JZctuN/Ino7d03hV/1CPxQRMo+Za5oM6mQ9JuNHxLOqnIZMRIgweK5wuJGmPo6scX9jvnu1EbHaQL35vEi9xde4aozoZsXo8v7us8/0krPTEYYmS70Iql6LdaT9T66td//oU7GxJ/MPJU+ClmIKZn/KyeoZjS3+xLKjxxKDP0BkljEkr9gfT+DkvnnqyIZfFEq+gsV1no3NO8dDaMfD+rSvL02zibJiOlpe4VaAGn9mJ0yDEeDdCQT5Hc1PoJu2ElhBiv8YlX+y8jLJfKiVsMThJ2M66PsZIzgxDJdZ3DrQSxmSqGREZ5iYNAI9BloIqjoJtpGQx2bCQ1/MxcHENswsTJZI5mZZbRCKiqkQzyhtVt8ylAsT1Zy4N3bi50=
deploy:
  provider: releases
  api_key:
    secure: Ep68eIsglRNPjapvEigGkhigaR0/sBqbdKJJf4OOVfkSaXKxIKpGQXKmhXYmSxHU0PLqnUvAh59tOku9QVGNPkKKDA6seykRLyAYTu8mbr0MmGAL4YqOTAUit+lzkSXKfW2XmM3QOZ13UJGzYFnigHqta4s5yxv5VAyxWf4Lt9BeAHttPyHOGlx3v/dGswwr2C0FuDo+i8P+zAI5l4ivcz75nA7IUFt0RjyaMi0b8xYFfSRT0F0J14lnl/3yixBEBqW897ekgWVcqFekYcAJWtyU1RkNOsdWl++SJ4s4NhQJ7lPC46TmcDFD3NrPC+CGhbmI1CIcMit5crpZJdqo0lSALRC8L92DrRxCt1R7gIfj9fwcqkLqHlz3KEmLWgsHr+ftnA8mQS4Cst5PyrfP2hdREJJwKW4o8TE7wdT+t9meWW2WPC48EnDqw/8FRby9dEf7PXo/u/jORJxZ15y8+bZe0x+RrfonK/5DoyTiFWo887VVLV+92QsGQPsN+auCNy/QYwEHwXS69ASAZaZeRW5rGTwMglPSHpOpJljWWQHD6Rh4+T4fNtpwC7V72c2gVvCOMdcb56Up8BOMNB2Ssijwr6EyC1hfNGPx55bOis4knpz6cofko9Hv6XRoRJTFQcQP+OegZg/a6G0BA7DsnH6g0myIanJiJp0ebF9c0eg=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-rancher-plugin

